package chatlan.GUI;

import chatlan.Client;
import chatlan.Message;
import java.awt.GridLayout;
import java.io.File;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;

/**
 *
 * @author philx
 */
public class ClientForm extends javax.swing.JFrame {

    public static Client _client;
    public String _address;
    public int _port;
    public Thread _clientThread;
    public String _userName;
    public DefaultListModel dlm;
    public Socket _socket;
    public ObjectOutputStream _OOS;
    public ObjectInputStream _OIS;
    public static File f;
    public Folder fd;
    public String[] uploader;
    public String[] filename;

    public void setSocket(Socket _socket) {
        this._socket = _socket;
    }

    public void setOIS(ObjectInputStream _OIS) {
        this._OIS = _OIS;
    }

    public void setOOS(ObjectOutputStream _OOS) {
        this._OOS = _OOS;
    }
            
    public void setUserName(String _userName) {
        this._userName = _userName;
    }

    public void setClient(Client _client) {
        this._client = _client;
    }

    public void setPort(int _port) {
        this._port = _port;
    }

    public void setClientThread(Thread _clientThread) {
        this._clientThread = _clientThread;
    }

    public void setAddress(String _address) {
        this._address = _address;
    }    
    
    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
        dlm = new DefaultListModel();
        dlm.addElement("All");
        lstUser.setModel(dlm);
        _port = 1996;
        txtMsg.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taDialog = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstUser = new javax.swing.JList<>();
        txtMsg = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        btnSendFile = new javax.swing.JButton();
        lblAvatar = new javax.swing.JLabel();
        btnChangePass = new javax.swing.JButton();
        btnChangeName = new javax.swing.JButton();
        lblChatwith = new javax.swing.JLabel();
        btnDownload = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        taDialog.setEditable(false);
        taDialog.setColumns(20);
        taDialog.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        taDialog.setLineWrap(true);
        taDialog.setRows(5);
        jScrollPane1.setViewportView(taDialog);

        lstUser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lstUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstUser);

        txtMsg.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtMsg.setText("Type your message here...");

        btnSend.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnSendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendFileActionPerformed(evt);
            }
        });

        btnChangePass.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        btnChangePass.setText("Change passowrd");
        btnChangePass.setBorderPainted(false);
        btnChangePass.setContentAreaFilled(false);
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        btnChangeName.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        btnChangeName.setText("Change name");
        btnChangeName.setBorderPainted(false);
        btnChangeName.setContentAreaFilled(false);
        btnChangeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeNameActionPerformed(evt);
            }
        });

        lblChatwith.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblChatwith.setText("jLabel1");

        btnDownload.setText("jButton1");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        btnUpload.setText("jButton1");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblChatwith)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDownload)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChangePass, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnChangeName, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSendFile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChangeName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChangePass))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChatwith)
                            .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnDownload)
                                .addComponent(btnUpload)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(btnSendFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lstUser.setSelectedIndex(0);
        setTitle("CTU CHAT - " + _userName);
        btnSendFile.setIcon(Reuse.Library.FitImageSize("image/ghim.png", btnSendFile.getWidth()-20, btnSendFile.getHeight()-20));
        btnSend.setIcon(Reuse.Library.FitImageSize("image/send.png", btnSend.getWidth()-20, btnSend.getHeight()-20));
    }//GEN-LAST:event_formWindowOpened

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        String msg = txtMsg.getText();
        if (msg.equals("/clear"))
            taDialog.setText("");
        else
        {
            Object[] sendTo = lstUser.getSelectedValues();
            for (int i = 0; i < sendTo.length; i++)
            {
                _client.send(new Message ("message",_userName,msg,sendTo[i].toString()));
            }
        }
        txtMsg.setText("");
    }//GEN-LAST:event_btnSendActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //TODO add your handling code here:
        _client.send(new Message ("off",_userName,_userName,"All"));
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnSendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendFileActionPerformed
        // TODO add your handling code here:
        Object[] receiver = lstUser.getSelectedValues();
        JFileChooser jfc = new JFileChooser();
        if (JFileChooser.APPROVE_OPTION == jfc.showOpenDialog(this))
        {            
            f = jfc.getSelectedFile();
        }
        if (f != null)
            for (int i = 0; i < receiver.length; i++)
                _client.send(new Message("sendFile",_userName, f.getName(),receiver[i].toString()));
    }//GEN-LAST:event_btnSendFileActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
        JPanel jp = new JPanel();
        JPasswordField pf = new JPasswordField();
        pf.setEchoChar('\u25cf');
        JPanel controls = new JPanel(new GridLayout(0, 1, 2, 2));
        controls.add(pf);
        int i = JOptionPane.showConfirmDialog(this, controls,"login", JOptionPane.OK_CANCEL_OPTION);
        if (i == 0)
        {
            if (pf.getText().equals(" "))
                JOptionPane.showMessageDialog(null, "illigal password!! type again");
            else
                changePass(pf.getText());
        }
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnChangeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeNameActionPerformed
        // TODO add your handling code here:
        String name = JOptionPane.showInputDialog(this,"Type your name:", "Change name", JOptionPane.DEFAULT_OPTION);
        if (name != null)
        {
            if (name.equals(" "))
                JOptionPane.showMessageDialog(null, "illigal name!! type again");
            else
                changeName(name);
        }
        setTitle("CTU CHAT - " + name);
    }//GEN-LAST:event_btnChangeNameActionPerformed

    private void lstUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstUserMouseClicked
        // TODO add your handling code here:
        Object[] n = lstUser.getSelectedValues();
        String _n = "Chatting with ";
        for (int i = 0; i < n.length; i++)
            _n += n[i].toString() + ", ";
        lblChatwith.setText(_n);
    }//GEN-LAST:event_lstUserMouseClicked

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        // TODO add your handling code here:
        _client.send(new Message("folder",_userName,"open","Server"));
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        if (JFileChooser.APPROVE_OPTION == jfc.showOpenDialog(this))
        {            
            f = jfc.getSelectedFile();
        }
        if (f != null)
            _client.send(new Message("upload",_userName,f.getName(),"Server"));
    }//GEN-LAST:event_btnUploadActionPerformed

    public void changeName (String un)
    {
        _client.send(new Message("name", _userName, un, "Server"));
    }
    
    public void changePass (String pass)
    {
        _client.send(new Message("pass", _userName, pass, "Server"));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeName;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSendFile;
    private javax.swing.JButton btnUpload;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblChatwith;
    public javax.swing.JList<String> lstUser;
    public javax.swing.JTextArea taDialog;
    private javax.swing.JTextField txtMsg;
    // End of variables declaration//GEN-END:variables
}
